### ISSUE TITLE
Indicate which issues I have already voted for in Active Sessions

### ISSUE THREAD

**Issue by XjeaxaxX** [codescape/jira-scrum-poker#106]
My admin starts many different poker sessions throughout the day.  When I go to Active Sessions... I have no idea which ones are new, or where I left off.  It would be nice to have some indication on this screen for the ones I have already voted in.   Otherwise, I have to click on every issue in the list to find out which one I have not yet voted on.  (I don't always vote in order of the list.)

**Comment by codescape** [comment]
Thank you very much for that feature idea. I very much like that idea and will implement it for one of the next releases!

**Comment by codescape** [comment]
This will be released today with version 20.05.1
