### ISSUE TITLE
Show "parent" task information for sub-tasks in poker view

### ISSUE THREAD

**Issue by XjeaxaxX** [codescape/jira-scrum-poker#110]
Quite often, we have a task contain almost all of the description information.  Then, we create a lot of sub-tasks... with simple phrases so we know what the job is.  For example, the "parent" task may be something like "Update all students and verify contact information".  With 70,000 students, we add sub-tasks for last names starting with "A-C", "D-F", "G", etc. etc.  

We actually play poker for our sub-tasks.  Because, in a given week, we may only be able to complete a few sub-tasks... not all of them.  So to track the work we do, we have to estimate sub-tasks.

The problem is that in the Poker view for a sub-task, I cannot see any information about the parent task.... which contains the information I need to see to be able to estimate.  Just seeing "A-C" doesn't tell me anything.  And there is no indication that it even has a parent task.

At a minimum, a link to the parent task would be nice.  Even better would be some way to also display the description of the parent task (to prevent the need to click on more things).

![2020-04-29_09h42_41](https://user-images.githubusercontent.com/1485215/80605038-82f5c780-8a00-11ea-8143-3b4f600f6c38.png)

In JIRA, when looking at a sub-task, the parent task is indicated in the links at the top:

![2020-04-29_09h45_17](https://user-images.githubusercontent.com/1485215/80605122-a4ef4a00-8a00-11ea-8d64-e91560fe9880.png)

**Comment by codescape** [comment]
Thank you very much. I very much understand your need for this and I think the proposed solution should be easy enough to find it’s way into one of the next versions!
