### ISSUE TITLE
Support for 1/2 card

### ISSUE THREAD

**Issue by XjeaxaxX** [codescape/jira-scrum-poker#111]
I added 1/2 to my configuration for card values.  The card shows, but nobody can click on it to vote for that value.  We do not use "0" because all tasks that we play poker for require *some* work... even if it is a simple text change.  But 1/2 is a great indicator that the work is very very minimal.  Many teams use 1/2 in their poker sets.

I also tried ".5".... but the same thing happened.

**Comment by codescape** [comment]
Thank you very much for this issue and your feedback! At the moment (Version 4.10) only non-decimal numbers are allowed and can be persisted into the estimate field.

This will be addressed with #102 where all values that are allowed by the underlying field can be saved.

I hope you are okay with this issue being closed and the solution being provided with #102.

**Comment by XjeaxaxX** [comment]
I did not see #102 .  Yes, that would work well.  For our estimation, we use a custom field which will accept fractions.... we don't use a "story point" field.

Thank you!

So far, we love your product!

**Comment by codescape** [comment]
Closing this issue with a solution being available when #102 is solved.

**Comment by codescape** [comment]
With 20.05.0 you can now have floating point values configured this way: 0.5
