### ISSUE TITLE
Configuration link for Scrum Poker add-on doesn't work and is reporting a bad link

### ISSUE THREAD

**Issue by Lentinis** [codescape/jira-scrum-poker#115]
Hello, I installed the Scrum Poker for Jira add-on on our JIRA. I am using a trial license and applied it but the Configuration link for this add-on doesn't work and is reporting a bad link so it's not configurable. Therefore the plug-in is not visible in my agile jira projects.

Please can you resolve this?

License SEN:
SEN-xxxxxxxxx

Thanks
Livinus

**Comment by codescape** [comment]
Hello @Lentinis, I just answered your mail before realizing you also opened an issue. I will keep this issue open and use it to document a solution if we find one together.

Best regards
Stefan

**Comment by codescape** [comment]
Another evaluation user reported the same problem. I asked him to provide details that might lead to the reason of this unexpected and unwanted behaviour.

**Comment by codescape** [comment]
I just found a potential reason for this problem and will provide a new version of Scrum Poker for Jira as soon as possible which has a solution for that.

The problem can be explained like this. Jira does not use the full name of a class but the simple name of a class to bind it to an action (a page). If this simple name is used among multiple plugins only one action will be generated and the second one will not be available. I guess this might be the case for the formerly called GlobalSettingsAction. This is now called ScrumPokerConfiguratoinAction.

**Comment by codescape** [comment]
Hello @Lentinis,

I was finally able to narrow this problem down to other plugins having a naming conflict with the configuration page. The latest version 20.06.1 is just released and addresses this problem.

**Comment by Lentinis** [comment]
Hi Stefan,

Thanks for letting me know. I trust you will be able to debug and find the fix for this.

Thanks

Livinus

**Comment by Lentinis** [comment]
Thanks Stefan.

Livinus

**Comment by Lentinis** [comment]
Hi Stefan,

Nice to hear you have found a fix for this. I will test this out and hope to get it working.

Thanks

Livinus

**Comment by codescape** [comment]
Please let me know. I am happy to hear from you.

**Comment by codescape** [comment]
Hello @Lentinis,

did you have a chance to already test the new version?

Thank you
Stefan

**Comment by codescape** [comment]
Hello @Lentinis,

do you have any news on this issue? I would like to close this issue if it is resolved.

Thank you
Stefan

**Comment by Lentinis** [comment]
Hi Stefan,

Sorry I have off for a while. As the trial Licence had expired, will it still be valid if I try a fresh new installation. Or will I need a new trial Licence?

Thanks

Livinus

**Comment by codescape** [comment]
Hello Livinus,

you just need to get a new free trial license and install the latest
version of Scrum Poker for Jira with it.

I am happy to hear from you.

Cheers,
Stefan

**Comment by Lentinis** [comment]
Hi Stefan,

Sorry for getting back to you this late. We did install the scrum poker ad-on with a new free Licence and I have tested it. Now it works good.

Thanks

Livinus

**Comment by codescape** [comment]
Hello Livinus,

thank you for your feedback. That's great to hear!

Cheers,
Stefan
