### ISSUE TITLE
Allow to cancel a session

### ISSUE THREAD

**Issue by ralfsch** [codescape/jira-scrum-poker#20]
It would be good to have the chance to cancel a poker session, if e. g. it was started by mistake or the discussion shows that the PO has to rework the story before it can be estimated. Currently the session stays on the list of active sessions.

**Comment by codescape** [comment]
Thank you very much! This idea will definately find its way into a future version.

**Comment by codescape** [comment]
What would you expect as a user when someone cancels the session? I am thinking of a message similar to the screen of a confirmed session informing the user and allowing to navigate to active sessions and back to the issue.

**Comment by ralfsch** [comment]
I think, that would be fine.

**Comment by codescape** [comment]
Implementation: At the moment only the creator of the session has a button to cancel the session which is displayed in the bottom line of buttons during a scrum poker session.
