### ISSUE TITLE
Enable Scrum Poker only for selected projects

### ISSUE THREAD

**Issue by ralfsch** [codescape/jira-scrum-poker#22]
A lot of our JIRA projects do not use Scrum Poker and are confused about the button. It would be good, if could enable/disable the AddOn per project.

**Comment by codescape** [comment]
Thank you very much! I understand the wish for configuration of this aspect. We need to find the correct place for the configuration since the button currently displays on boards (can hold multiple projects) and on issues (can only belong to a single project).

**Comment by ralfsch** [comment]
Maybe for boards you could show the button, if at least one of the projects has Scrum Poker enabled and hide it, if none of the included projects uses it.

**Comment by codescape** [comment]
Scrum Poker can now be globally enabled for all projects or globally disabled and individually enabled for projects.

See: 66a32c1f0c8416f4b542f3e97047ba4bb39f6eab and 01afa7cc271b46b83b26f30835879bbd9f5cd400

The Scrum Poker dropdown in boards is not yet improved.

**Comment by codescape** [comment]
I filed a feature request for a better API to access the Boards from the plugin: 
https://ecosystem.atlassian.net/servicedesk/customer/portal/14/DEVHELP-2134
