### ISSUE TITLE
Create a warning if the configured estimation field is not configured in the project

### ISSUE THREAD

**Issue by benoitjoh** [codescape/jira-scrum-poker#26]
If I start scrum poker in a project that uses an other field for estimation than the configured one from scrumpoker, the results are not stored. 
A warning would be great.

**Comment by codescape** [comment]
Thank you very much. It is planned to configure Scrum Poker plugin per project in the future and I hope this will solve your problem, too. In my vision you can then use different fields in different projects and mark Scrum Poker as available or not available in the project configuration.

**Comment by codescape** [comment]
I will work on the following solution:

* Scrum Poker session can be started for any editable issue with the configured estimation field 
* estimations can only be confirmed by users who have the permission to edit the issue

This should leave no path that leads to a Scrum Poker session where the estimation cannot be saved.

**Comment by codescape** [comment]
I will add a notification for the user saving the estimation that tells about success or error while saving the estimation for the given issue.

    AJS.flag({
        type: 'success',
        body: 'Estimation for issue <strong>SPP-12</strong> saved successfully.',
        close: 'auto'
    });

For the error message and further documentation see: https://docs.atlassian.com/aui/7.9.3/docs/flag.html
