### ISSUE TITLE
Cloud compatibility

### ISSUE THREAD

**Issue by vulkman** [codescape/jira-scrum-poker#27]
Hey man,

love dat plugin but can't use it in muh Jira cuz not available for use in Atlassian Cloud instances.

Any idea wot 2 do 2 get dat? I'd buy that for a dolla!

Cheers

**Comment by vulkman** [comment]
Update: I googled muhself some info, y'all just have to agree to some shit and it's done :)

https://developer.atlassian.com/platform/marketplace/app-approval-guidelines/#additional-criteria-for-cloud-apps

**Comment by codescape** [comment]
I am sorry but developing for Atlassian Jira Cloud is completely different to developing Atlassian Jira Server plugins.

See this thread for more information:

https://community.atlassian.com/t5/Answers-Developer-Questions/How-to-developed-an-addon-both-for-jira-cloud-and-server/qaq-p/472793

Currently I have not planned to create a Cloud compatible version of the plugin.

**Comment by vulkman** [comment]
Daaaamn, well, maybe I'll just write one then
