### ISSUE TITLE
Button "Start Scrum Poker" shown twice

### ISSUE THREAD

**Issue by ralfsch** [codescape/jira-scrum-poker#28]
The button "Start Scrum Poker" is shown twice in the issue detail view (on the left and on the right).

![scrumpoker twice](https://user-images.githubusercontent.com/1277711/43075466-40566a78-8e81-11e8-8680-1445a01f01b4.PNG)

**Comment by codescape** [comment]
Hey @ralfsch,

thank you for that issue! Can you share some details to the installation of your Jira like version number and installed plugins? I guess there is some plugin that duplicates buttons configured for some web sections as I am unable to reproduce this issue with a clean installation up to Jira 7.11.0.

Affected Code:

https://github.com/codescape/jira-scrum-poker/blob/master/src/main/resources/atlassian-plugin.xml#L39-L51

**Comment by ralfsch** [comment]
Hi @codescape,

We tested with JIRA 7.6.3. 

List of AddOns:
- Field Sync
- JIRA Suite Utilities
- Portfolio for JIRA
- JIRA Misc Workflow Extensions
- Tempo
- nFeed
- Email This Issue
- Mobility for JIRA
- Intenso Utils

**Comment by codescape** [comment]
Hello @ralfsch,

I could reproduce your issue with a user with limited rights to issues where the user has no right to assign issues. Then the next button available from the "More" dropdown will be shown next to the dropdown and this is in fact the "Start Scrum Poker" button. I will try to find a better solution for this redundancy.

**Comment by codescape** [comment]
Solution: I moved the menu item to the other menu items with relation to Jira Software and the Agile Boards.
![image](https://user-images.githubusercontent.com/398901/43945147-93a23618-9c81-11e8-8888-b5621f61f78e.png)
