### ISSUE TITLE
Provide QR code to join Scrum Poker session on mobile devices

### ISSUE THREAD

**Issue by flogger007** [codescape/jira-scrum-poker#39]
How can the team members join session and select card during  the meeting?
We can start session on meeting room computer but rest of members don't have one. Is these any mobile app for this poker?

**Comment by codescape** [comment]
At the moment Scrum Poker does not provide any mobile app to join a Scrum Poker session. I will change the title of the issue and keep it as a great feature addition to this add-on.

**Comment by codescape** [comment]
QR code can be rendered with JS only: https://davidshimjs.github.io/qrcodejs/ or http://jeromeetienne.github.io/jquery-qrcode/

**Comment by codescape** [comment]
QR Code is now available together with a "copy link" option via share button on the session page:

f57fff1fc72780528e7a55518038f52acec2e003
