### ISSUE TITLE
Allow the Reveal button to be only clickable by the creator of the session

### ISSUE THREAD

**Issue by dfjones1981** [codescape/jira-scrum-poker#41]
We'd like to prevent the participants from revealing the card selections too early. If it were possible that the reveal button is only clickable by the person who created the planning session, that would seem to fix the issue. Thanks!

**Comment by codescape** [comment]
Hello @dfjones1981, thank you for your request. I understand the need for being able to restrict this but I would not implement this as a hard coded feature and would prefer to make it available as a configuration option.

**Comment by dfjones1981** [comment]
yeah that makes sense, it might not suit everyone's needs

**Comment by codescape** [comment]
I will implement this feature with three configuration options:

* CREATOR - Only the creator of the session can reveal the deck.
* EVERYONE - Everyone can reveal the deck.
* PARTICIPANTS - Only participants who have provided a vote can reveal the deck.

**Comment by codescape** [comment]
solved with 99555f60c8af5f3c717bd0135127bf50731ee316

**Comment by codescape** [comment]
comes with 3.9.0
