### ISSUE TITLE
Allow to jump back to where you started Scrum Poker from

### ISSUE THREAD

**Issue by codescape** [codescape/jira-scrum-poker#53]
Use the returnUrl again and allow to jump back. The method getReturnUrl() returns something like `/secure/RapidBoard.jspa?rapidView=1&view=planning&selectedIssue=BBB-3&issueLimit=100` or `null` if there is no url to return to.

**Comment by codescape** [comment]
The method getReturnUrl() returns something like `/secure/RapidBoard.jspa?rapidView=1&view=planning&selectedIssue=BBB-3&issueLimit=100` or `null` if there is no Url to return to.

**Comment by greghoeppner** [comment]
Any chance this item can be prioritized? We would really like going back to where we started.

**Comment by codescape** [comment]
@greghoeppner Hello Greg, I will look into this issue for the next release.

**Comment by codescape** [comment]
Implementation is ready. This feature will be included in the upcoming version.

**Comment by greghoeppner** [comment]
@codescape Thank you so much!

**Comment by codescape** [comment]
The new version 22.05.0 has already been shipped yesterday.
