### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by LegrandYoann** [codescape/jira-scrum-poker#59]
Hello, 

We evaluated your app, it's a great apps, we like it !

But after our evaluation, we detected two suggestions to improve your app : 

1. How to launch a session for all issues of a Sprint ?
As a Product Owner, I put stories from my backlog to the next sprint in my JIRA Board.
I would like to launch a poker planning session for all issues in my next sprint with only one click.
For now , I need to launch a poker planning session for all stories one by one.

2. How to manage cards into the Poker Planning by project ?
We have many projects, the Project A use Fibonacci  and this project can use Scrum Poker.
But another Project B prefers to do a poker planning with another value , like "1,3,5,7,9" or"1,2,3,4,5", or ...
Would it be possible to configure the scale of story points in the project admin section, if not at the Jira admin level.

Thanks in advance for your feedback,

**Comment by codescape** [comment]
Hello @LegrandYoann,

thank you very much for your great feedback! I would like to raise a new issue for your first idea. I have no specific idea how to implement this yet but it sounds like an interesting improvement.

Your second idea is already adressed by the open issue #18.

Cheers,
Stefan

**Comment by codescape** [comment]
Closing this issue and tracking requirements in both separate issues #18 and #61.
