### ISSUE TITLE
can't configure "Show Dropdown on Boards"

### ISSUE THREAD

**Issue by gnomegemini** [codescape/jira-scrum-poker#93]
If you try to enable the option, "Default Project Activation" get's enabled/ disabled instead.
![2020-01-22_08h10_42](https://user-images.githubusercontent.com/11074820/72872902-ba145880-3cee-11ea-9179-8aadb6513a7d.png)

**Comment by codescape** [comment]
Thank you very much, @gnomegemini!

As long as the fix is not available one can still click on the select box itself and not the label to select this option.
