### ISSUE TITLE
Nullpointer excpetion when saving saving after clicking "alle Kommentare anzeigen"

### ISSUE THREAD

**Issue by gnomegemini** [codescape/jira-scrum-poker#96]

**Comment by gnomegemini** [comment]
Narf... counting is difficult. Sorry I Closed: #97 not this #96. But by the way: what's the correct way to go to initiate a PR:
1. creating an issue
2. fixing it
3. do a PR closing this issue

or
1. fixing it
2. look for latest issue
3. generate PR and closing itself?

Kind regards,
Stefan

**Comment by codescape** [comment]
Hello @gnomegemini, thank you for that issue and the PR! 

My personal preference would be the following way but everything is welcome and fine!

1. create the issue and describe the problem
2. fix it (not everyone is able to do that, so it might stop here)
3. create a PR and reference the issue

When merging I normally add a commit with the changes in the changelog and close the issue with the merge.

Thank you for your contribution!
Stefan
